-- sqlfluff:exclude_rules:ST06
SELECT
    TRIP_ID::NUMBER AS TRIP_ID,
    VENDORID::NUMBER AS VENDORID,
    TO_TIMESTAMP_NTZ(TPEP_PICKUP_DATETIME / 1000000)::TIMESTAMP_NTZ(0) AS TPEP_PICKUP_DATETIME,
    TO_TIMESTAMP_NTZ(TPEP_DROPOFF_DATETIME / 1000000)::TIMESTAMP_NTZ(0) AS TPEP_DROPOFF_DATETIME,
    PASSENGER_COUNT::NUMBER AS PASSENGER_COUNT,
    TRIP_DISTANCE::NUMBER(10, 2) AS TRIP_DISTANCE,
    RATECODEID::NUMBER AS RATECODEID,
    CASE
        WHEN STORE_AND_FWD_FLAG = 'Y' THEN TRUE
        WHEN STORE_AND_FWD_FLAG = 'N' THEN FALSE
    END AS STORE_AND_FWD_FLAG,
    PULOCATIONID::NUMBER AS PULOCATIONID,
    DOLOCATIONID::NUMBER AS DOLOCATIONID,
    PAYMENT_TYPE::NUMBER AS PAYMENT_TYPE,
    FARE_AMOUNT::NUMBER(10, 2) AS FARE_AMOUNT,
    EXTRA::NUMBER(10, 2) AS EXTRA,
    MTA_TAX::NUMBER(10, 2) AS MTA_TAX,
    TIP_AMOUNT::NUMBER(10, 2) AS TIP_AMOUNT,
    TOLLS_AMOUNT::NUMBER(10, 2) AS TOLLS_AMOUNT,
    IMPROVEMENT_SURCHARGE::NUMBER(10, 2) AS IMPROVEMENT_SURCHARGE,
    TOTAL_AMOUNT::NUMBER(10, 2) AS TOTAL_AMOUNT,
    CONGESTION_SURCHARGE::NUMBER(10, 2) AS CONGESTION_SURCHARGE,
    AIRPORT_FEE::NUMBER(10, 2) AS AIRPORT_FEE,
    CBD_CONGESTION_FEE::NUMBER(10, 2) AS CBD_CONGESTION_FEE
FROM {{ source('raw', 'YELLOW_TAXI_TRIPS_RAW') }}
WHERE
    TRIP_DISTANCE >= 0
    AND TOTAL_AMOUNT > 0
    AND FARE_AMOUNT > 0
    AND TPEP_PICKUP_DATETIME IS NOT NULL
    AND TPEP_DROPOFF_DATETIME IS NOT NULL
    AND TPEP_PICKUP_DATETIME < TPEP_DROPOFF_DATETIME
    AND PULOCATIONID IS NOT NULL
    AND DOLOCATIONID IS NOT NULL
