-- sqlfluff:exclude_rules:ST06
SELECT
    VENDORID,
    TO_TIMESTAMP_NTZ(TPEP_PICKUP_DATETIME / 1000000) AS TPEP_PICKUP_DATETIME,
    TO_TIMESTAMP_NTZ(TPEP_DROPOFF_DATETIME / 1000000) AS TPEP_DROPOFF_DATETIME,
    PASSENGER_COUNT,
    TRIP_DISTANCE,
    RATECODEID,
    STORE_AND_FWD_FLAG,
    PULOCATIONID,
    DOLOCATIONID,
    TRIM(PAYMENT_TYPE) AS PAYMENT_TYPE,
    CAST(FARE_AMOUNT AS DECIMAL(10, 2)) AS FARE_AMOUNT,
    EXTRA,
    MTA_TAX,
    TIP_AMOUNT,
    TOLLS_AMOUNT,
    IMPROVEMENT_SURCHARGE,
    TOTAL_AMOUNT,
    CONGESTION_SURCHARGE,
    AIRPORT_FEE,
    CBD_CONGESTION_FEE
FROM {{ source('raw', 'YELLOW_TAXI_TRIPS_RAW') }}
WHERE
    TRIP_DISTANCE >= 0
    AND TOTAL_AMOUNT > 0
    AND FARE_AMOUNT > 0
    AND TPEP_PICKUP_DATETIME IS NOT NULL
    AND TPEP_DROPOFF_DATETIME IS NOT NULL
    AND TPEP_PICKUP_DATETIME < TPEP_DROPOFF_DATETIME
    AND PULOCATIONID IS NOT NULL
    AND DOLOCATIONID IS NOT NULL
