USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS { ROLE_TRANSFORMER };

CREATE USER IF NOT EXISTS { USER_DEV }
PASSWORD='{ PASSWORD_DEV }'
LOGIN_NAME='{ USER_DEV }'
MUST_CHANGE_PASSWORD=FALSE
DEFAULT_WAREHOUSE='{ WH_NAME }'
DEFAULT_ROLE='{ ROLE_TRANSFORMER }'
DEFAULT_NAMESPACE='{ DW_NAME }.{ RAW_SCHEMA }'
COMMENT='Utilisateur Snowflake pour ingestion et transformations DBT';

GRANT ROLE { ROLE_TRANSFORMER } TO USER { USER_DEV };
GRANT ROLE { ROLE_TRANSFORMER } TO ROLE SYSADMIN;
