USE ROLE SYSADMIN;

GRANT ALL ON WAREHOUSE { WH_NAME } TO ROLE { ROLE_TRANSFORMER };
GRANT ALL ON DATABASE { DW_NAME } TO ROLE { ROLE_TRANSFORMER };
GRANT ALL ON ALL SCHEMAS IN DATABASE { DW_NAME } TO ROLE { ROLE_TRANSFORMER };
GRANT ALL ON FUTURE SCHEMAS IN DATABASE { DW_NAME } TO ROLE { ROLE_TRANSFORMER };
GRANT ALL ON ALL TABLES IN SCHEMA { DW_NAME }.{ RAW_SCHEMA } TO ROLE { ROLE_TRANSFORMER };
GRANT ALL ON FUTURE TABLES IN SCHEMA { DW_NAME }.{ RAW_SCHEMA } TO ROLE { ROLE_TRANSFORMER };
GRANT USAGE ON FILE FORMAT { DW_NAME }.{ RAW_SCHEMA }.{ PARQUET_FORMAT } TO ROLE { ROLE_TRANSFORMER };
