CREATE WAREHOUSE IF NOT EXISTS { WH_NAME }
WITH WAREHOUSE_SIZE = 'X-SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS { DW_NAME };
CREATE SCHEMA IF NOT EXISTS { DW_NAME }.{ RAW_SCHEMA };
CREATE FILE FORMAT IF NOT EXISTS { DW_NAME }.{ RAW_SCHEMA }.{ PARQUET_FORMAT } TYPE='PARQUET';
