NYC_Taxi_dbt:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      warehouse: "{{ env_var('WH_NAME') }}"
      database: "{{ env_var('DW_NAME') }}"
      schema: SCHEMA
      user: "{{ env_var('USER_DEV') }}"
      password: "{{ env_var('PASSWORD_DEV') }}"
      role: "{{ env_var('ROLE_TRANSFORMER') }}"
      threads: 1
  target: dev