USE DATABASE DW_NAME_PLACEHOLDER;

CREATE BACKUP POLICY IF NOT EXISTS DW_NAME_PLACEHOLDER_POLICY
  SCHEDULE = 'USING CRON 0 12 1 * * UTC'
  EXPIRE_AFTER_DAYS = FULL_BACKUP_POLICY_DAYS_PLACEHOLDER
  COMMENT = 'Full Backup Policy for database DW_NAME_PLACEHOLDER';

CREATE BACKUP POLICY IF NOT EXISTS RAW_TABLE_PLACEHOLDER_POLICY
  SCHEDULE = 'USING CRON 0 12 1 * * UTC'
  EXPIRE_AFTER_DAYS = RAW_TABLE_BACKUP_POLICY_DAYS_PLACEHOLDER
  COMMENT = 'Backup Policy for table RAW_TABLE_PLACEHOLDER';

CREATE BACKUP POLICY IF NOT EXISTS SCHEMA_FINAL_SCHEMA_PLACEHOLDER_POLICY
  SCHEDULE = 'USING CRON 0 12 1 * * UTC'
  EXPIRE_AFTER_DAYS = FINAL_SCHEMA_BACKUP_POLICY_DAYS_PLACEHOLDER
  COMMENT = 'Backup Policy for schema FINAL_SCHEMA_PLACEHOLDER';

CREATE BACKUP SET IF NOT EXISTS DW_NAME_PLACEHOLDER_BACKUP
  FOR DATABASE DW_NAME_PLACEHOLDER
  WITH BACKUP POLICY DW_NAME_PLACEHOLDER_POLICY
  COMMENT = 'Backup set for the complete database DW_NAME_PLACEHOLDER';

CREATE BACKUP SET IF NOT EXISTS RAW_TABLE_PLACEHOLDER_BACKUP
  FOR TABLE DW_NAME_PLACEHOLDER.SCHEMA_RAW_SCHEMA_PLACEHOLDER.RAW_TABLE_PLACEHOLDER
  WITH BACKUP POLICY RAW_TABLE_PLACEHOLDER_POLICY
  COMMENT = 'Backup set for table RAW_TABLE_PLACEHOLDER in schema RAW_SCHEMA_PLACEHOLDER';

CREATE BACKUP SET IF NOT EXISTS FINAL_SCHEMA_PLACEHOLDER_BACKUP
  FOR SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_FINAL_SCHEMA_PLACEHOLDER
  WITH BACKUP POLICY FINAL_SCHEMA_PLACEHOLDER_POLICY
  COMMENT = 'Backup set for schema FINAL_SCHEMA_PLACEHOLDER in database DW_NAME_PLACEHOLDER';