USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ROLE_TRANSFORMER_PLACEHOLDER;

CREATE USER IF NOT EXISTS USER_DEV_PLACEHOLDER
    PASSWORD = 'PASSWORD_DEV_PLACEHOLDER'
    LOGIN_NAME = 'USER_DEV_PLACEHOLDER'
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_WAREHOUSE = 'WH_NAME_PLACEHOLDER'
    DEFAULT_ROLE = 'ROLE_TRANSFORMER_PLACEHOLDER'
    DEFAULT_NAMESPACE = 'DW_NAME_PLACEHOLDER.RAW_SCHEMA_PLACEHOLDER'
    COMMENT = 'Utilisateur Snowflake pour ingestion et transformations DBT';

GRANT ROLE ROLE_TRANSFORMER_PLACEHOLDER TO USER USER_DEV_PLACEHOLDER;
GRANT ROLE ROLE_TRANSFORMER_PLACEHOLDER TO ROLE SYSADMIN;
