USE ROLE SECURITYADMIN;

-- Create transformer role
CREATE ROLE IF NOT EXISTS ROLE_TRANSFORMER_PLACEHOLDER;
COMMENT ON ROLE ROLE_TRANSFORMER_PLACEHOLDER IS 'Role for data transformation (DBT)';

-- Create transformer user
CREATE USER IF NOT EXISTS USER_DEV_PLACEHOLDER
    PASSWORD = 'PASSWORD_DEV_PLACEHOLDER'
    LOGIN_NAME = 'USER_DEV_PLACEHOLDER'
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_WAREHOUSE = 'WH_NAME_PLACEHOLDER'
    DEFAULT_ROLE = 'ROLE_TRANSFORMER_PLACEHOLDER'
    DEFAULT_NAMESPACE = 'DW_NAME_PLACEHOLDER.RAW_SCHEMA_PLACEHOLDER'
    COMMENT = 'Snowflake user for DBT ingestion and transformations';

-- Assign transformer role
GRANT ROLE ROLE_TRANSFORMER_PLACEHOLDER TO USER USER_DEV_PLACEHOLDER;
GRANT ROLE ROLE_TRANSFORMER_PLACEHOLDER TO ROLE SYSADMIN;

-- Create business roles
CREATE ROLE IF NOT EXISTS ROLE_BI_ANALYST_PLACEHOLDER;
COMMENT ON ROLE ROLE_BI_ANALYST_PLACEHOLDER IS 'Role for BI analysts (read access to FINAL modeled data)';

CREATE ROLE IF NOT EXISTS ROLE_DATA_SCIENTIST_PLACEHOLDER;
COMMENT ON ROLE ROLE_DATA_SCIENTIST_PLACEHOLDER IS 'Role for data scientists (read access to STAGING and DIM/FACT in FINAL data)';

CREATE ROLE IF NOT EXISTS ROLE_MART_CONSUMER_PLACEHOLDER;
COMMENT ON ROLE ROLE_MART_CONSUMER_PLACEHOLDER IS 'Role for business consumers (read access to aggregated marts)';

-- Create business users
CREATE USER IF NOT EXISTS USER_BI_ANALYST_PLACEHOLDER
    PASSWORD = 'PASSWORD_BI_PLACEHOLDER'
    LOGIN_NAME = 'USER_BI_ANALYST_PLACEHOLDER'
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_WAREHOUSE = 'WH_NAME_PLACEHOLDER'
    DEFAULT_ROLE = 'ROLE_BI_ANALYST_PLACEHOLDER'
    COMMENT = 'BI Analyst user';

CREATE USER IF NOT EXISTS USER_DATA_SCIENTIST_PLACEHOLDER
    PASSWORD = 'PASSWORD_DS_PLACEHOLDER'
    LOGIN_NAME = 'USER_DATA_SCIENTIST_PLACEHOLDER'
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_WAREHOUSE = 'WH_NAME_PLACEHOLDER'
    DEFAULT_ROLE = 'ROLE_DATA_SCIENTIST_PLACEHOLDER'
    COMMENT = 'Data Scientist user';

CREATE USER IF NOT EXISTS USER_MART_CONSUMER_PLACEHOLDER
    PASSWORD = 'PASSWORD_MC_PLACEHOLDER'
    LOGIN_NAME = 'USER_MART_CONSUMER_PLACEHOLDER'
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_WAREHOUSE = 'WH_NAME_PLACEHOLDER'
    DEFAULT_ROLE = 'ROLE_MART_CONSUMER_PLACEHOLDER'
    COMMENT = 'Mart Consumer user';

-- Assign roles to users
GRANT ROLE ROLE_BI_ANALYST_PLACEHOLDER TO USER USER_BI_ANALYST_PLACEHOLDER;
GRANT ROLE ROLE_DATA_SCIENTIST_PLACEHOLDER TO USER USER_DATA_SCIENTIST_PLACEHOLDER;
GRANT ROLE ROLE_MART_CONSUMER_PLACEHOLDER TO USER USER_MART_CONSUMER_PLACEHOLDER;