USE ROLE SYSADMIN;

GRANT ALL ON WAREHOUSE WH_NAME_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;
GRANT ALL ON DATABASE DW_NAME_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;
GRANT ALL ON ALL SCHEMAS IN DATABASE DW_NAME_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE DW_NAME_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;
GRANT ALL ON ALL TABLES IN SCHEMA DW_NAME_PLACEHOLDER.RAW_SCHEMA_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;
GRANT ALL ON FUTURE TABLES IN SCHEMA DW_NAME_PLACEHOLDER.RAW_SCHEMA_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;
GRANT USAGE ON FILE FORMAT DW_NAME_PLACEHOLDER.RAW_SCHEMA_PLACEHOLDER.PARQUET_FORMAT_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;
