USE ROLE SYSADMIN;

-- Transformer role permissions
GRANT ALL ON WAREHOUSE WH_NAME_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;
GRANT ALL ON DATABASE DW_NAME_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;
GRANT ALL ON ALL SCHEMAS IN DATABASE DW_NAME_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE DW_NAME_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;
GRANT ALL ON ALL TABLES IN SCHEMA DW_NAME_PLACEHOLDER.RAW_SCHEMA_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;
GRANT ALL ON FUTURE TABLES IN SCHEMA DW_NAME_PLACEHOLDER.RAW_SCHEMA_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;
GRANT USAGE ON FILE FORMAT DW_NAME_PLACEHOLDER.RAW_SCHEMA_PLACEHOLDER.PARQUET_FORMAT_PLACEHOLDER TO ROLE ROLE_TRANSFORMER_PLACEHOLDER;


-- BI Analyst role permissions (Read on FINAL)
GRANT USAGE ON DATABASE DW_NAME_PLACEHOLDER TO ROLE ROLE_BI_ANALYST_PLACEHOLDER;
GRANT USAGE ON SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_FINAL_SCHEMA_PLACEHOLDER TO ROLE ROLE_BI_ANALYST_PLACEHOLDER;
GRANT SELECT ON ALL TABLES IN SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_FINAL_SCHEMA_PLACEHOLDER TO ROLE ROLE_BI_ANALYST_PLACEHOLDER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_FINAL_SCHEMA_PLACEHOLDER TO ROLE ROLE_BI_ANALYST_PLACEHOLDER;


-- Data Scientist role permissions (Read on STAGING and DIM/FACT in FINAL)
GRANT USAGE ON DATABASE DW_NAME_PLACEHOLDER TO ROLE ROLE_DATA_SCIENTIST_PLACEHOLDER;
GRANT USAGE ON SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_STAGING_SCHEMA_PLACEHOLDER TO ROLE ROLE_DATA_SCIENTIST_PLACEHOLDER;
GRANT SELECT ON ALL TABLES IN SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_STAGING_SCHEMA_PLACEHOLDER TO ROLE ROLE_DATA_SCIENTIST_PLACEHOLDER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_STAGING_SCHEMA_PLACEHOLDER TO ROLE ROLE_DATA_SCIENTIST_PLACEHOLDER;

GRANT USAGE ON SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_FINAL_SCHEMA_PLACEHOLDER TO ROLE ROLE_DATA_SCIENTIST_PLACEHOLDER;
GRANT SELECT ON ALL TABLES IN SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_FINAL_SCHEMA_PLACEHOLDER TO ROLE ROLE_DATA_SCIENTIST_PLACEHOLDER;
REVOKE SELECT ON ALL VIEWS IN SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_FINAL_SCHEMA_PLACEHOLDER FROM ROLE ROLE_DATA_SCIENTIST;
REVOKE SELECT ON FUTURE VIEWS IN SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_FINAL_SCHEMA_PLACEHOLDER FROM ROLE ROLE_DATA_SCIENTIST;

-- Mart Consumer role permissions (Read on VIEWS in FINAL)
GRANT USAGE ON DATABASE DW_NAME_PLACEHOLDER TO ROLE ROLE_MART_CONSUMER_PLACEHOLDER;
GRANT USAGE ON SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_FINAL_SCHEMA_PLACEHOLDER TO ROLE ROLE_MART_CONSUMER_PLACEHOLDER;
GRANT SELECT ON ALL VIEWS IN SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_FINAL_SCHEMA_PLACEHOLDER TO ROLE ROLE_MART_CONSUMER_PLACEHOLDER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DW_NAME_PLACEHOLDER.SCHEMA_FINAL_SCHEMA_PLACEHOLDER TO ROLE ROLE_MART_CONSUMER_PLACEHOLDER;