CREATE WAREHOUSE IF NOT EXISTS WH_NAME_PLACEHOLDER
WITH WAREHOUSE_SIZE = 'COMPUTE_SIZE_PLACEHOLDER' -- noqa: PRS
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS DW_NAME_PLACEHOLDER;
CREATE SCHEMA IF NOT EXISTS DW_NAME_PLACEHOLDER.SCHEMA_RAW_SCHEMA_PLACEHOLDER;
CREATE FILE FORMAT IF NOT EXISTS DW_NAME_PLACEHOLDER.SCHEMA_RAW_SCHEMA_PLACEHOLDER.PARQUET_FORMAT_PLACEHOLDER TYPE = 'PARQUET';
CREATE SCHEMA IF NOT EXISTS DW_NAME_PLACEHOLDER.SCHEMA_STAGING_SCHEMA_PLACEHOLDER;
CREATE SCHEMA IF NOT EXISTS DW_NAME_PLACEHOLDER.SCHEMA_FINAL_SCHEMA_PLACEHOLDER;