CREATE TRANSIENT TABLE IF NOT EXISTS METADATA_TABLE_PLACEHOLDER (
    FILE_URL VARCHAR(255),
    FILE_NAME VARCHAR(55),
    YEAR NUMBER(4, 0),
    MONTH NUMBER(2, 0),
    ROWS_LOADED NUMBER(10, 0),
    LOAD_STATUS VARCHAR(55),
    LOAD_TIMESTAMP TIMESTAMP_TZ DEFAULT CONVERT_TIMEZONE('TIMEZONE_PLACEHOLDER', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ))
)
