CREATE TABLE IF NOT EXISTS METADATA_TABLE_PLACEHOLDER (
    FILE_URL VARCHAR(500),
    FILE_NAME VARCHAR(250),
    YEAR NUMBER,
    MONTH NUMBER,
    ROWS_LOADED NUMBER,
    LOAD_STATUS VARCHAR(12),
    LOAD_TIMESTAMP TIMESTAMP_TZ DEFAULT CONVERT_TIMEZONE('Europe/Paris', CURRENT_TIMESTAMP())
)
