name: 'NYC_Taxi_dbt'
version: '1.0.0'

profile: 'NYC_Taxi_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

models:
  NYC_Taxi_dbt:
    staging:
      int_trip_metrics:
        +materialized: view
        +schema: "{{ env_var('STAGING_SCHEMA') }}"
      yellow_taxi_trips_stg:
        +materialized: table  
        +schema: "{{ env_var('STAGING_SCHEMA') }}"
    final:
      +materialized: table
      +schema: "{{ env_var('FINAL_SCHEMA') }}"
    marts:
      +materialized: view
      +schema: "{{ env_var('FINAL_SCHEMA') }}"